### ISSUE TITLE
Steps to run this application

### ISSUE THREAD

**Issue by caeser1996** [HarisSpahija/fit_kit_example#1]
Can you please tell me the exact steps to run this application your kind consideration is highly appreciated.

**Comment by jeroen-meijer** [comment]
- Plug in a phone or start an emulator.
- `flutter run`

More info can be found [here](https://flutter.dev/docs/get-started/test-drive?tab=terminal).
This repo will most likely be purged soon, so it's best to run [the package's example](https://github.com/krokyze/FitKit/tree/master/example) instead.

For more help, please consider using one of [these community channels](https://flutter.dev/community).

**Comment by caeser1996** [comment]
That is not working actually. Please help me .it's not authenticating the
application.

**Comment by jeroen-meijer** [comment]
I can't really help you with the description you gave me.
Also, this is not my repository, so please direct all debugging questions to the [original repo (https://github.com/krokyze/fitkit)](https://github.com/krokyze/fitkit).

Hope this helps.
Good luck.

Closing.

**Comment by HarisSpahija** [comment]
Hi @caeser1996 , like @jeroen-meijer said this is a fork from https://github.com/krokyze/FitKit/tree/master/example 

Please refer to that repo. I will perge this repo probably tomorrow.
